<meta name="robots" content="noindex"/>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="author" content="Amnesty International, International Secretariat" />
<meta name="copyright" content="The copyright for this material rests with Amnesty International. You may not alter this information, repost or sell it without prior permission." />
<title>Library - Amnesty International</title>
<meta name="Description" content="Amnesty International (AI) is a worldwide movement of people who campaign for internationally recognized human rights." />
<meta name="Keywords" content="human rights, amnesty international, AI, international secretariat, justice, death penalty, armed conflict, violence against women, activists, human rights defenders, refugees, war on terror, torture, universal declaration of human rights, take action, campaigns" />
<link href="http://www.amnesty.org/amnesty.css" rel="stylesheet" type="text/css" /><script language="JavaScript" src="http://www.amnesty.org/js/validateAIIndexSearch.js" type="text/JavaScript"></script>
<script language="JavaScript" type="text/javascript" src="http://www.amnesty.org/js/validateEmailToFriendForm.js"></script>