package org.amnesty.aidoc.search;

import java.util.HashMap;

public class CategoryToClassMap {
    
    public static HashMap<String, String> hm = new HashMap<String, String>();
    static {
        hm.put("AFRICA", "AFR 01");
        hm.put("CENTRAL AFRICA", "AFR 02");
        hm.put("SOUTHERN AFRICA", "AFR 03");
        hm.put("EAST AFRICA", "AFR 04");
        hm.put("WEST AFRICA", "AFR 05");
        hm.put("ANGOLA", "AFR 12");
        hm.put("BENIN", "AFR 14");
        hm.put("BOTSWANA", "AFR 15");
        hm.put("BURUNDI", "AFR 16");
        hm.put("CAMEROON", "AFR 17");
        hm.put("CAPE VERDE", "AFR 18");
        hm.put("CENTRAL AFRICAN REPUBLIC", "AFR 19");
        hm.put("CHAD", "AFR 20");
        hm.put("COMOROS", "AFR 21");
        hm.put("CONGO", "AFR 22");
        hm.put("DJIBOUTI", "AFR 23");
        hm.put("EQUATORIAL GUINEA", "AFR 24");
        hm.put("ETHIOPIA", "AFR 25");
        hm.put("GABON", "AFR 26");
        hm.put("GAMBIA", "AFR 27");
        hm.put("GHANA", "AFR 28");
        hm.put("GUINEA", "AFR 29");
        hm.put("GUINEA-BISSAU", "AFR 30");
        hm.put("COTE D'IVOIRE", "AFR 31");
        hm.put("KENYA", "AFR 32");
        hm.put("LESOTHO", "AFR 33");
        hm.put("LIBERIA", "AFR 34");
        hm.put("MADAGASCAR", "AFR 35");
        hm.put("MALAWI", "AFR 36");
        hm.put("MALI", "AFR 37");
        hm.put("MAURITANIA", "AFR 38");
        hm.put("MAURITIUS", "AFR 39");
        hm.put("MOZAMBIQUE", "AFR 41");
        hm.put("NAMIBIA", "AFR 42");
        hm.put("NIGER", "AFR 43");
        hm.put("NIGERIA", "AFR 44");
        hm.put("REUNION", "AFR 45");
        hm.put("ZIMBABWE", "AFR 46");
        hm.put("RWANDA", "AFR 47");
        hm.put("SAO TOME AND PRINCIPE", "AFR 48");
        hm.put("SENEGAL", "AFR 49");
        hm.put("SEYCHELLES", "AFR 50");
        hm.put("SIERRA LEONE", "AFR 51");
        hm.put("SOMALIA", "AFR 52");
        hm.put("SOUTH AFRICA", "AFR 53");
        hm.put("SUDAN", "AFR 54");
        hm.put("SWAZILAND", "AFR 55");
        hm.put("TANZANIA", "AFR 56");
        hm.put("TOGO", "AFR 57");
        hm.put("UGANDA", "AFR 59");
        hm.put("BURKINA FASO", "AFR 60");
        hm.put("DEMOCRATIC REPUBLIC OF CONGO", "AFR 62");
        hm.put("ZAMBIA", "AFR 63");
        hm.put("ERITREA", "AFR 64");
        hm.put("AMERICAS", "AMR 01");
        hm.put("CENTRAL AMERICA", "AMR 02");
        hm.put("SOUTH AMERICA", "AMR 03");
        hm.put("NORTH AMERICA", "AMR 04");
        hm.put("CARIBBEAN", "AMR 05");
        hm.put("ANGUILLA", "AMR 11");
        hm.put("ANTILLES", "AMR 12");
        hm.put("ARGENTINA", "AMR 13");
        hm.put("BAHAMAS", "AMR 14");
        hm.put("BARBADOS", "AMR 15");
        hm.put("BELIZE", "AMR 16");
        hm.put("BERMUDA", "AMR 17");
        hm.put("BOLIVIA", "AMR 18");
        hm.put("BRAZIL", "AMR 19");
        hm.put("CANADA", "AMR 20");
        hm.put("CAYMAN ISLANDS", "AMR 21");
        hm.put("CHILE", "AMR 22");
        hm.put("COLOMBIA", "AMR 23");
        hm.put("COSTA RICA", "AMR 24");
        hm.put("CUBA", "AMR 25");
        hm.put("DOMINICA", "AMR 26");
        hm.put("DOMINICAN REPUBLIC", "AMR 27");
        hm.put("ECUADOR", "AMR 28");
        hm.put("EL SALVADOR", "AMR 29");
        hm.put("FALKLAND ISLANDS", "AMR 30");
        hm.put("FRENCH GUIANA", "AMR 31");
        hm.put("GRENADA", "AMR 32");
        hm.put("GUADELOUPE", "AMR 33");
        hm.put("GUATEMALA", "AMR 34");
        hm.put("GUYANA", "AMR 35");
        hm.put("HAITI", "AMR 36");
        hm.put("HONDURAS", "AMR 37");
        hm.put("JAMAICA", "AMR 38");
        hm.put("MARTINIQUE", "AMR 40");
        hm.put("MEXICO", "AMR 41");
        hm.put("MONTSERRAT", "AMR 42");
        hm.put("NICARAGUA", "AMR 43");
        hm.put("PANAMA", "AMR 44");
        hm.put("PARAGUAY", "AMR 45");
        hm.put("PERU", "AMR 46");
        hm.put("PUERTO RICO", "AMR 47");
        hm.put("SURINAME", "AMR 48");
        hm.put("TRINIDAD & TOBAGO", "AMR 49");
        hm.put("TURKS & CAICOS ISLANDS", "AMR 50");
        hm.put("USA", "AMR 51");
        hm.put("URUGUAY", "AMR 52");
        hm.put("VENEZUELA", "AMR 53");
        hm.put("VIRGIN ISLANDS (UK)", "AMR 54");
        hm.put("ST LUCIA", "AMR 56");
        hm.put("ST VINCENT", "AMR 57");
        hm.put("ANTIGUA & BARBUDA", "AMR 58");
        hm.put("ST KITTS-NEVIS", "AMR 59");
        hm.put("VIRGIN ISLANDS (US)", "AMR 60");
        hm.put("ARUBA", "AMR 61");
        hm.put("ASIA AND THE PACIFIC", "ASA 01");
        hm.put("EAST ASIA", "ASA 02");
        hm.put("SOUTH-EAST ASIA", "ASA 03");
        hm.put("SOUTH ASIA", "ASA 04");
        hm.put("PACIFIC", "ASA 05");
        hm.put("AFGHANISTAN", "ASA 11");
        hm.put("AUSTRALIA", "ASA 12");
        hm.put("BANGLADESH", "ASA 13");
        hm.put("BHUTAN", "ASA 14");
        hm.put("BRUNEI DARUSSALAM", "ASA 15");
        hm.put("MYANMAR", "ASA 16");
        hm.put("CHINA", "ASA 17");
        hm.put("FIJI", "ASA 18");
        hm.put("HONG KONG", "ASA 19");
        hm.put("INDIA", "ASA 20");
        hm.put("INDONESIA", "ASA 21");
        hm.put("JAPAN", "ASA 22");
        hm.put("CAMBODIA", "ASA 23");
        hm.put("NORTH KOREA", "ASA 24");
        hm.put("SOUTH KOREA", "ASA 25");
        hm.put("LAOS", "ASA 26");
        hm.put("MACAO", "ASA 27");
        hm.put("MALAYSIA", "ASA 28");
        hm.put("MALDIVES", "ASA 29");
        hm.put("MONGOLIA", "ASA 30");
        hm.put("NEPAL", "ASA 31");
        hm.put("NEW ZEALAND", "ASA 32");
        hm.put("PAKISTAN", "ASA 33");
        hm.put("PAPUA NEW GUINEA", "ASA 34");
        hm.put("PHILIPPINES", "ASA 35");
        hm.put("SINGAPORE", "ASA 36");
        hm.put("SRI LANKA", "ASA 37");
        hm.put("TAIWAN", "ASA 38");
        hm.put("THAILAND", "ASA 39");
        hm.put("TONGA", "ASA 40");
        hm.put("VIET NAM", "ASA 41");
        hm.put("NAURU", "ASA 42");
        hm.put("SOLOMON ISLANDS", "ASA 43");
        hm.put("VANUATU", "ASA 44");
        hm.put("WESTERN SAMOA", "ASA 45");
        hm.put("KIRIBATI", "ASA 46");
        hm.put("TUVALU", "ASA 47");
        hm.put("NEW CALEDONIA", "ASA 48");
        hm.put("PALAU", "ASA 49");
        hm.put("FRENCH POLYNESIA", "ASA 50");
        hm.put("MARSHALL ISLANDS", "ASA 51");
        hm.put("MICRONESIA", "ASA 52");
        hm.put("COOK ISLANDS", "ASA 53");
        hm.put("NIUE", "ASA 54");
        hm.put("GUAM", "ASA 55");
        hm.put("AMERICAN SAMOA", "ASA 56");
        hm.put("TIMOR LESTE", "ASA 57");
        hm.put("PITCAIRN ISLANDS", "ASA 58");
        hm.put("EUROPE AND CENTRAL ASIA", "EUR 01");
        hm.put("EASTERN EUROPE", "EUR 02");
        hm.put("WESTERN EUROPE", "EUR 03");
        hm.put("COMMONWEALTH OF INDEPENDENT STATES", "EUR 04");
        hm.put("BALKANS", "EUR 05");
        hm.put("BALTIC STATES", "EUR 06");
        hm.put("EURASIA", "EUR 07");
        hm.put("ALBANIA", "EUR 11");
        hm.put("ANDORRA", "EUR 12");
        hm.put("AUSTRIA", "EUR 13");
        hm.put("BELGIUM", "EUR 14");
        hm.put("BULGARIA", "EUR 15");
        hm.put("CYPRUS", "EUR 17");
        hm.put("DENMARK", "EUR 18");
        hm.put("FAROE ISLANDS", "EUR 19");
        hm.put("FINLAND", "EUR 20");
        hm.put("FRANCE", "EUR 21");
        hm.put("GERMANY", "EUR 23");
        hm.put("GIBRALTAR", "EUR 24");
        hm.put("GREECE", "EUR 25");
        hm.put("GREENLAND", "EUR 26");
        hm.put("HUNGARY", "EUR 27");
        hm.put("ICELAND", "EUR 28");
        hm.put("IRELAND", "EUR 29");
        hm.put("ITALY", "EUR 30");
        hm.put("LIECHTENSTEIN", "EUR 31");
        hm.put("LUXEMBOURG", "EUR 32");
        hm.put("MALTA", "EUR 33");
        hm.put("MONACO", "EUR 34");
        hm.put("NETHERLANDS", "EUR 35");
        hm.put("NORWAY", "EUR 36");
        hm.put("POLAND", "EUR 37");
        hm.put("PORTUGAL", "EUR 38");
        hm.put("ROMANIA", "EUR 39");
        hm.put("SAN MARINO", "EUR 40");
        hm.put("SPAIN", "EUR 41");
        hm.put("SWEDEN", "EUR 42");
        hm.put("SWITZERLAND", "EUR 43");
        hm.put("TURKEY", "EUR 44");
        hm.put("UK", "EUR 45");
        hm.put("RUSSIAN FEDERATION", "EUR 46");
        hm.put("VATICAN", "EUR 47");
        hm.put("BELARUS", "EUR 49");
        hm.put("UKRAINE", "EUR 50");
        hm.put("ESTONIA", "EUR 51");
        hm.put("LATVIA", "EUR 52");
        hm.put("LITHUANIA", "EUR 53");
        hm.put("ARMENIA", "EUR 54");
        hm.put("AZERBAIJAN", "EUR 55");
        hm.put("GEORGIA", "EUR 56");
        hm.put("KAZAKSTAN", "EUR 57");
        hm.put("KYRGYZSTAN", "EUR 58");
        hm.put("MOLDOVA", "EUR 59");
        hm.put("TAJIKISTAN", "EUR 60");
        hm.put("TURKMENISTAN", "EUR 61");
        hm.put("UZBEKISTAN", "EUR 62");
        hm.put("BOSNIA-HERZEGOVINA", "EUR 63");
        hm.put("CROATIA", "EUR 64");
        hm.put("MACEDONIA", "EUR 65");
        hm.put("MONTENEGRO", "EUR 66");
        hm.put("SLOVENIA", "EUR 68");
        hm.put("SERBIA", "EUR 70");
        hm.put("CZECH REPUBLIC", "EUR 71");
        hm.put("SLOVAK REPUBLIC", "EUR 72");
        hm.put("MIDDLE EAST AND NORTH AFRICA", "MDE 01");
        hm.put("MIDDLE EAST", "MDE 02");
        hm.put("NORTH AFRICA", "MDE 03");
        hm.put("GULF STATES", "MDE 04");
        hm.put("EAST GULF", "MDE 05");
        hm.put("WEST GULF", "MDE 06");
        hm.put("EAST MEDITERRANEAN", "MDE 07");
        hm.put("BAHRAIN", "MDE 11");
        hm.put("EGYPT", "MDE 12");
        hm.put("IRAN", "MDE 13");
        hm.put("IRAQ", "MDE 14");
        hm.put("ISRAEL/OCCUPIED TERRITORIES", "MDE 15");
        hm.put("JORDAN", "MDE 16");
        hm.put("KUWAIT", "MDE 17");
        hm.put("LEBANON", "MDE 18");
        hm.put("LIBYA", "MDE 19");
        hm.put("OMAN", "MDE 20");
        hm.put("PALESTINIAN AUTHORITY", "MDE 21");
        hm.put("QATAR", "MDE 22");
        hm.put("SAUDI ARABIA", "MDE 23");
        hm.put("SYRIA", "MDE 24");
        hm.put("UAE", "MDE 25");
        hm.put("ALGERIA", "MDE 28");
        hm.put("MOROCCO", "MDE 29");
        hm.put("TUNISIA", "MDE 30");
        hm.put("YEMEN", "MDE 31");
        hm.put("BALKANS", "REG 01");
        hm.put("EU MCAP", "REG 02");
        hm.put("NORTH AFRICA MCAP", "REG 03");
        hm.put("ISRAEL/OT/PA", "REG 04");
    }

}
